import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Molecules/Header";
import WindowBox from "@/components/Organism/WindowBox";

export default function Home() {
  return (
    <>
      <Head>
        <title>AI STORY TELLER</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="icons8-scroll-64.png" />
      </Head>
      <main className={styles.main}>
        <Header title="AI-Story-Teller" />

        <div className={styles.content}>
          <WindowBox title="Enter Story Info" />
        </div>
      </main>
    </>
  );
}
